[package]
name="biblyst"
version="0.1.0"
entrypoint="multi-bib.typ"
authors=[
    "Paul Adam @pauladam94"
]
license="MIT"
description="Manage acronyms and their definitions in Typst."
repository="https://github.com/pauladam94/multi-bib"
keywords=["bib", "bibliography"]
categories=["bibliography"]
